#!/bin/bash


NC='\033[0m' # no color
RED='\033[0;31m'
BLUE='\033[0;34m'


# Program
g++ -pthread main.cpp -o executable_main.out
./executable_main.out

echo -e '\n\n\n'

# Author
printf '_%.0s' {1..100}
echo -e "@author ${BLUE}github.com/AlimKugot/Operating-System${NC}"


# Clean up
rm executable_main.out
